name: Testing runners

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'feature/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# Example flow

jobs:
  run_tests:
    name: Run Tests
    runs-on: windows
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          clean: true